# Generated by Django 2.2.16 on 2022-05-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220428_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=123, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moderator', 'Модератор'), ('admin', 'Администратор'), ('user', 'Пользователь')], default='user', max_length=50, verbose_name='Роль пользователя'),
        ),
    ]
