# Generated by Django 2.2.16 on 2022-05-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220503_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Код авторизации'),
        ),
    ]
